# Boolean Functions & Networks Toolbox — Interactive Tutorials

Welcome! These notebooks walk you through the main features of the provided toolbox for **analysis** and **random generation** of Boolean functions and networks (with applications to gene regulatory networks).

**How to use these notebooks**
- Run the first cell to import the toolbox from the local files you provided.
- Each section contains small runnable examples, expected outputs, and short exercises.
- Cells marked **🔧 Try it** are meant for you to edit and explore.

> If you update the Python files, just re-run the import cell to pick up changes.


## 0. Setup & Imports

In [2]:
import numpy as np
import boolforge

print('boolforge functions:', len([f for f in dir(boolforge) if callable(getattr(boolforge,f, None)) and not f.startswith('_')]))
print([f for f in dir(boolforge) if callable(getattr(boolforge,f, None)) and not f.startswith('_')])

boolforge functions: 37
['BF', 'BooleanFunction', 'BooleanNetwork', 'Optional', 'SeedSequence', 'Union', 'bin2dec', 'bool_to_poly', 'check_if_empty', 'dec2bin', 'default_rng', 'defaultdict', 'f_from_expression', 'flatten', 'get_layer_structure_from_canalized_outputs', 'get_layer_structure_of_an_NCF_given_its_Hamming_weight', 'get_left_side_of_truth_table', 'is_list_or_array_of_floats', 'is_list_or_array_of_ints', 'random_NCF', 'random_degenerated_function', 'random_degrees', 'random_edge_list', 'random_function', 'random_function_with_bias', 'random_function_with_exact_hamming_weight', 'random_k_canalizing_function', 'random_k_canalizing_function_with_specific_layer_structure', 'random_linear_function', 'random_nested_canalizing_function', 'random_network', 'random_non_canalizing_function', 'random_non_canalizing_non_degenerated_function', 'random_non_degenerated_function', 'random_null_model', 'random_wiring_diagram', 'rewire_wiring_diagram']


## 1. Building a small Boolean Network
We'll build a 3-node network with simple update rules and examine basic properties.

In [40]:
# Define update rules by truth tables

# Network: x0 <- x2 AND x3 ; x1 <- x1 OR x3 ; x2 <- NOT x1
F = [
    [0,0,0,1],     # AND on 2 inputs (x1,x2)
    [0,1,1,0],     # OR on 2 inputs (x0,x2)
    [1,1]          # identity on 1 input (x1)
]
I = [
    [1,2],  # regulators of x0 are x1,x2
    [0,2],  # regulators of x1 are x0,x2
    [1],    # regulator of x2 is x1
]

bn = boolforge.BooleanNetwork(F,I)

# Evaluate synchronous update from a given state
state = np.array([0,1,1], dtype=int)
next_state = bn.update_network_synchronously(state)
print(f"{state} -> {next_state}")

result = bn.get_attractors_synchronous_exact()
print(result)

[0 1 1] -> [1 1 1]
{'Attractors': [[np.int64(7)]], 'NumberOfAttractors': 1, 'BasinSizes': [8], 'AttractorDict': {0: 0, np.int64(5): 0, np.int64(7): 0, 1: 0, 2: 0, 3: 0, 4: 0, 6: 0}, 'STG': array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])}


## 2. State space, attractors, and basins

In [24]:
# Explore the synchronous state transition graph to find attractors, basin sizes, etc
print('All attractors assuming a synchronous update scheme')
attractor_info_sync = bn.get_attractors_synchronous_exact()
for key in attractor_info_sync:
    print(f"{key}: {attractor_info_sync[key]}")

print()
print('Steady states assuming an asynchronous update scheme')
attractor_info_async = bn.get_steady_states_asynchronous(EXACT=True)
for key in attractor_info_async:
    print(f"{key}: {attractor_info_async[key]}")

All attractors assuming a synchronous update scheme
Attractors: [[np.int64(7)]]
NumberOfAttractors: 1
BasinSizes: [8]
AttractorDict: {0: 0, np.int64(7): 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0}
STG: [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Steady states assuming an asynchronous update scheme
SteadyStates: [np.int64(4), np.int64(5), np.int64(6), np.int64(7)]
NumberOfSteadyStates: 4
BasinSizes: [2, 2, 2, 2]
SteadyStateDict: {np.int64(4): 0, np.int64(5): 1, np.int64(6): 2, np.int64(7): 3}
FunctionTransitionDict: {(0, np.int64(0)): np.int64(4), (np.int64(4), np.int64(1)): np.int64(4), (np.int64(4), np.int64(0)): np.int64(4), (np.int64(4), np.int64(2)): np.int64(4), (1, np.int64(0)): np.int64(5), (np.int64(5), np.int64(2)): np.int64(5), (np.int64(5), np.int64(0)): np.int64(5), (np.int64(5), np.int64(1)): np.int64(5), (2, np.int64(0)): np.int64(6), (np.int64(6), np.int64(0)): np.int64(6), (np.int64(6), np.int64(1)): np.int64(6), (np.int64(6), np.int64(2)): np.i

## 3. Sensitivity & Derrida plots (if available)

In [ ]:
# If the toolbox has Derrida or sensitivity on networks, demonstrate here
try:
    derrida = BN.derrida_curve(F, I, samples=200, seed=1)
    print('Derrida (Hamming distance mapping): first 5 points ->', derrida[:5])
except Exception as e:
    print('Derrida utility not available:', e)

## 4. Structural properties: in/out degree, frozen nodes, etc.

In [ ]:
try:
    indeg = BN.in_degrees(I)
    outdeg = BN.out_degrees(I, N=len(F))
    print('in-degrees:', indeg)
    print('out-degrees:', outdeg)
except Exception as e:
    print('Degree helpers not available:', e)

try:
    frozen = BN.get_frozen_nodes(F, I, samples=200, seed=0)
    print('frozen nodes (estimated):', frozen)
except Exception as e:
    print('Frozen node estimator not available:', e)

## 🔧 Try it: Your network here

In [ ]:
# Edit F and I to define your own network, then re-run the attractor finder above.
F = [
    np.array([0,1,1,1], dtype=int),  # OR(x2,x3)
    np.array([0,1,1,0], dtype=int),  # XOR(x1,x3)
    np.array([1,0], dtype=int)       # NOT(x1)
]
I = [[1,2],[0,2],[0]]
print('Defined a new network of size', len(F))